### PR TITLE
Modifications to asp encodings and tree structure; allows for more arbitrary piles

### PR DESCRIPTION
**Pull request by atreyasha**
### 1. clingo encoding for `nim`

Modified clingo `background.lp`.

1. Now, the terminal state occurs when only one element is left on the `last_pile`. This reduces the need to compute final empty steps, might be slightly faster.

2. Also, now we can add arbitrarily many piles without adjusting the rules, it is integrated with `#sum` calls in `clingo`.

3. Symmetry has been added into `background.lp`. This means it will ignore doing multiple removes if there are symmetric piles present.

### 2. Minimax in `Tree` class

Integrated `expand_root` as internal function instead of class function. Added minimax construction as part of `Tree` class.

### 3. `nim` game definition

Modified the ascii-plotting functions such that we can make arbitrarily large visualizations. Also, removed the top bar of `-` elements to save some space, but this can be adjusted back if it was better. There was a bug with previous version where not all elements were being visualized.

This change also allows for arbitrarily many piles without requiring hard-coding, as per `self.number_piles` and `self.maximum_number`.

### 4. `step` ascii score

Changed `ascii` score visualization for summary of minimax structure to be shown on root node.

### 5. Visualization

Added html conversion for prettier visualizations of games. Provided two means of visualizing games from the `Tree` class, either [with](https://github.com/atreyasha/asp-game-strategies/blob/develop_mx_mc/src/img/test_tree_html.png) or [without](https://github.com/atreyasha/asp-game-strategies/blob/develop_mx_mc/src/img/test_tree_plain.png) html.

### 6. Main function structure

Separated `main.py` into `main_match.py` for simulating matches, and `main_mx_tree.py` for building minimax trees.

## Additional actions to prevent conflicts

If all this is fine, we would need to make minor adjustments to `full_time.lp` encodings to have similar constraints as the modified `background.lp` scripts. Also, we might need to adjust `min_max_asp.py`.

Also, some of the tests under `/src/tests` are giving odd results, so might need to look through these again.

### CODE REVIEW

**Comment by atreyasha** [comment]
> Is everything duplicated in the test file because of import issues?

Yes that is right. It is not duplicated though, those are just symlinks to the previous directories, so the same amount of space (more or less, minus a tiny symlink).

> What is this signature for?

When running the code via command-line or another system, it helps the system identify exactly which python version you are using and also what encoding the file has. It is just a practice for exporting scripts.

> What is the prupose of arg_metav_formatter.py?

If you see the readme in the `develop_mx_mc` branch, there are usage or help scripts. Similarly, if you execute `$ python main_build_tree.py --help`, you come across a helper script. The parameters, defaults and argument types are formatted through `arg_metav_formatter.py`.

> I dont fully understand your changes in the background.lp file. Do they really make it faster? The reason why I didnt use sum or min is becase ILASP does not allow that syntax. I also feel like if the game ends when there one player takes the last thing then it should still be a valid move... What was the reason for this change, so that I understand the full thing. I get the idea of removing the symetry but for this last step I dont get it. 

The final step of taking out the last piece corresponds to `n` additional steps at the end of computation, where `n` corresponds to the number of leaves. For small games, this is negligible. For large games, this will contribute to running the final step again, which might be inefficient. It also looks slightly weird to have an empty grid in every last step, but that it just my POV.

And about the `#sum` and `#min` syntax, I did not know ILASP can't parse it. Then we might have to change this, but it makes things faster and more agnostic with clingo alone.

> For the html option, any idea how we could make it not dependet to the game?,because at the moment it works just for nim but what if we have anotehr game like tic tac toe, then maybe we should think of how to export parts of the funcion to the game definition like it is done for the to ascii, that allowed different represenatations depending on the game.

Yes, this is what I wanted to do as well. However, this would require that we change the way steps are plotted, ie. we would need to store all fluents in some kind of numpy array and plot them later. I did not want to conflict with the `ascii_score`'s, so I just left it like that. But tbh, if we only stick to `nim` this is fine. I think it is also better to just stick to `nim` for now so that we have more depth than breadth.

> I found a bug in line 86 of game_def it should be:
new_line = (step.action.player+" ")*(n) + lines[p][(n)*2:]
Otherwise the prints are wrong.

For the visualizations that I did, this did not constitute a bug (ie. my visualizations still make sense). But I did notice that the visualizations are wrong when simulating the match. Maybe there is some discrepancy somewhere. Or is it also wrong for my visualizations (ie. images)?

**Comment by susuhahnml** [comment]
Ok. I just feel like all the work already done to make everything not dependent on the game makes it worth it to edit that function. But we can check that latter.

**Comment by susuhahnml** [comment]
I dont feel like that last timestep is wrong, it would not be empty, in the tree it would show the last action of one player taking the last balls.

**Comment by atreyasha** [comment]
I will just respond to the points and then summarize for feedback.

> Ok. I just feel like all the work already done to make everything not dependent on the game makes it worth it to edit that function. But we can check that latter.

Yes we can add this to our tasks.

> I dont feel like that last timestep is wrong, it would not be empty, in the tree it would show the last action of one player taking the last balls.

The last timestep is not necessarily *wrong*, I would just argue that it is redundant since we already know that the terminal state occurs when one piece is left on the last pile, so we don't *have* to have the player take the last piece. I mean tbh there would be very little difference in our context on the speed, so it is fine either ways.

Okay so here is a summary of things for me to change (in decreasing priority), let me know whether you agree/disagree with these:

1. Remove `#sum` and `#min` calls in `background.lp` and revert to explicitly declared dimensions, so that this works with ILASP.

2. Revert the terminal state back to the original state, ie. allow the player to consume the last piece on the last pile before terminating. But there is a counter-argument and counter-example to this in the comment below.

3. Fix the bug related to ascii plotting as you mentioned above, but let me know an instance when this bug occurs so I can test and fix it.

4. Edit the plotting function for html tables to be agnostic of the ascii function, maybe by storing the state in some numpy array which is plotted later on.

Only thing with points 1 and 2 is that some of work I did would become redundant :smile:, but I guess that is just part of the process. I will be really busy with work and moving, so I will try to edit these whenever I get time. Let me know if some changes are urgent so I can do it asap.

For me, a priority would be to merge this pull request, so we can develop the rest of the things to write our paper. So I would want to make the necessary changes needed for a merge, so I can then focus on the next steps.

**Comment by atreyasha** [comment]
Ah yes, I remember why I changed the `background.lp` to do what it does with the last piece. As per wikipedia's definition of `nim`:

> Nim is a mathematical game of strategy in which two players take turns removing (i.e., nimming) objects from distinct heaps or piles. On each turn, a player must remove at least one object, and may remove any number of objects provided they all come from the same heap/pile. Depending on the version being played, the goal of the game is either to avoid taking the last object, or to take the last object

So the whole winning strategy has to do with the last object. But I noticed in the old `background.lp`, the important line for `legal` moves was:

```
legal(X,remove(P,N)) :- true(has(P,M)), removable(N), N<=M, 
true(control(X)), not terminal.
```

The issue I found is that we allow for `N <= M`, which means a player can technically take the whole pile on the last pile, which would leave out the possibility of having one piece left on the last pile. I wanted to have the game configured such that every terminal step will have one piece left on the last pile. That is the motivation for why I added this thing with the `last_pile` atom.

I thought of an example where this could be problematic. In the old `background.lp`, the winning trigger is as such:

```
goal(X,1):- true(has(1,0)), true(has(2,0)), true(has(3,0)), true(control(X)).
```

Assume the case where we have the last pile as `**` and player `b` is playing. If we follow the old `background.lp`, player `b` can take the entire pile and then player `a` will win as per the condition above. Player `b` can also take one `*` and then player `a` will lose.

However, if we use the new `background.lp`, player `b` can only take one `*` as per the rules of nim, and then player `a` will lose.

By changing `background.lp`, I just wanted to avoid such cases where a player can consume the whole last pile, which I think should not be the case.

Edit: But apparently, there are different formulations of the game, so maybe I had a different formulation in mind. Anw let me know what you think.

**Comment by susuhahnml** [comment]
If think the point about if we leave this last step or not we can discuss in person as it only affects that file and we still have the old version. With this in mind I would also not care so much about the changing sum and min for ILASP because is not that straight forward and we can leave that discussion once we decide on the best strategy and see how ILASP comes to play. 

I am tring to fix myslef the strange bug on the ascci representation. I can keep doing that tomorrow so that it works both for printing in the console and on the trees. As soon as I fix this bug we can merge this PR and then talk about the definition on of the game in person. I belive we also should talk about how we present what we are doing, like redefine the objective of the project. However I think this is also something to talk in person.

**Pull request merged**
